package com.avonix.profitness.core.theme

/** All user-visible strings for the app, available in Turkish and English. */
data class AppStrings(
    // Profile – metrics section
    val performanceMetrics  : String,
    val seeAll              : String,
    // Profile – weekly activity
    val weeklyActivity      : String,
    val thisWeekSummary     : String,
    val dayAbbreviations    : List<String>,
    val unitDays            : String,
    val unitStreak          : String,
    // Profile – metric card labels
    val fatRatioLabel       : String,
    val muscleMassLabel     : String,
    val activeDaysLabel     : String,
    val dailyStreakLabel     : String,
    val bmiLabel            : String,
    val weeklyCaloriesLabel : String,
    // Profile – trophy subtitles
    val trophyFirstWin      : String,
    val trophySevenDay      : String,
    val trophyFiftyWorkouts : String,
    val trophySuperMember   : String,
    val trophyExcellence    : String,
    val trophyEliteLabel    : String,
    // Profile – trophies section header
    val achievements        : String,
    // Settings section
    val accountSettings     : String,
    val editProfileHint     : String,
    val notificationsLabel  : String,
    val notificationsActive : String,
    val notificationsOff    : String,
    val languageLabel       : String,
    val currentLanguageName : String,
    val securityLabel       : String,
    val securityValue       : String,
    val logoutLabel         : String,
    // Appearance sheet
    val appearanceTitle     : String,
    val modeLabel           : String,
    val darkLabel           : String,
    val lightLabel          : String,
    val accentColorLabel    : String,
    val applyLabel          : String,
    // Notifications sheet
    val notifSheetTitle     : String,
    val workoutReminders    : String,
    val progressUpdates     : String,
    val newsAlerts          : String,
    // Language sheet
    val langSheetTitle      : String,
    val turkishLabel        : String,
    val englishLabel        : String,
)

val TurkishStrings = AppStrings(
    performanceMetrics  = "PERFORMANS ÖLÇÜTLERİ",
    seeAll              = "Tümünü Gör",
    weeklyActivity      = "HAFTALIK AKTİVİTE",
    thisWeekSummary     = "Bu hafta 5 antrenman",
    dayAbbreviations    = listOf("Pzt", "Sal", "Çrş", "Per", "Cum", "Cmt", "Paz"),
    unitDays            = "gün",
    unitStreak          = "seri",
    fatRatioLabel       = "YAĞ ORANI",
    muscleMassLabel     = "KAS KÜTLESİ",
    activeDaysLabel     = "AKTİF GÜN",
    dailyStreakLabel     = "GÜNLÜK SERİ",
    bmiLabel            = "VÜCUT KİTLE İND.",
    weeklyCaloriesLabel = "HAFTALIK KALORİ",
    trophyFirstWin      = "İlk Zafer",
    trophySevenDay      = "7 Günlük",
    trophyFiftyWorkouts = "50 Antrenman",
    trophySuperMember   = "Süper Üye",
    trophyExcellence    = "Mükemmellik",
    trophyEliteLabel    = "ELİTE",
    achievements        = "BAŞARILAR",
    accountSettings     = "HESAP VE AYARLAR",
    editProfileHint     = "Profili düzenlemek için dokun",
    notificationsLabel  = "Bildirimler",
    notificationsActive = "Aktif",
    notificationsOff    = "Kapalı",
    languageLabel       = "Dil",
    currentLanguageName = "Türkçe",
    securityLabel       = "Güvenlik",
    securityValue       = "Yüksek",
    logoutLabel         = "Çıkış Yap",
    appearanceTitle     = "GÖRÜNÜM AYARLARI",
    modeLabel           = "MOD",
    darkLabel           = "KARANLIK",
    lightLabel          = "AYDINLIK",
    accentColorLabel    = "VURGU RENGİ",
    applyLabel          = "UYGULA",
    notifSheetTitle     = "BİLDİRİM AYARLARI",
    workoutReminders    = "Antrenman Hatırlatmaları",
    progressUpdates     = "İlerleme Güncellemeleri",
    newsAlerts          = "Haber Bildirimleri",
    langSheetTitle      = "DİL SEÇİMİ",
    turkishLabel        = "Türkçe",
    englishLabel        = "English",
)

val EnglishStrings = AppStrings(
    performanceMetrics  = "PERFORMANCE METRICS",
    seeAll              = "See All",
    weeklyActivity      = "WEEKLY ACTIVITY",
    thisWeekSummary     = "5 workouts this week",
    dayAbbreviations    = listOf("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"),
    unitDays            = "days",
    unitStreak          = "streak",
    fatRatioLabel       = "BODY FAT",
    muscleMassLabel     = "MUSCLE MASS",
    activeDaysLabel     = "ACTIVE DAYS",
    dailyStreakLabel     = "DAILY STREAK",
    bmiLabel            = "BODY MASS IDX",
    weeklyCaloriesLabel = "WEEKLY CALORIES",
    trophyFirstWin      = "First Victory",
    trophySevenDay      = "7-Day Streak",
    trophyFiftyWorkouts = "50 Workouts",
    trophySuperMember   = "Super Member",
    trophyExcellence    = "Excellence",
    trophyEliteLabel    = "ELITE",
    achievements        = "ACHIEVEMENTS",
    accountSettings     = "ACCOUNT & SETTINGS",
    editProfileHint     = "Tap to edit profile",
    notificationsLabel  = "Notifications",
    notificationsActive = "Active",
    notificationsOff    = "Off",
    languageLabel       = "Language",
    currentLanguageName = "English",
    securityLabel       = "Security",
    securityValue       = "High",
    logoutLabel         = "Log Out",
    appearanceTitle     = "APPEARANCE SETTINGS",
    modeLabel           = "MODE",
    darkLabel           = "DARK",
    lightLabel          = "LIGHT",
    accentColorLabel    = "ACCENT COLOR",
    applyLabel          = "APPLY",
    notifSheetTitle     = "NOTIFICATION SETTINGS",
    workoutReminders    = "Workout Reminders",
    progressUpdates     = "Progress Updates",
    newsAlerts          = "News Alerts",
    langSheetTitle      = "LANGUAGE",
    turkishLabel        = "Türkçe",
    englishLabel        = "English",
)

/** Convenience extension to get strings for the current language. */
val AppThemeState.strings: AppStrings
    get() = if (language == AppLanguage.ENGLISH) EnglishStrings else TurkishStrings
