revoke execute on function public.create_event_challenge(
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    double precision,
    double precision,
    text,
    text,
    bigint,
    text,
    text,
    jsonb,
    double precision,
    double precision,
    text,
    text,
    uuid
) from public;

grant execute on function public.create_event_challenge(
    text,
    text,
    text,
    text,
    text,
    text,
    text,
    double precision,
    double precision,
    text,
    text,
    bigint,
    text,
    text,
    jsonb,
    double precision,
    double precision,
    text,
    text,
    uuid
) to authenticated;
